In [31]:
import os
import numpy as np
import librosa
import tensorflow as tf
from sklearn.model_selection import train_test_split
from model import EnvNet
from train import train_model
from data_preprocess import make_frames,make_frames_folder
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Conv1D,MaxPooling1D,Dense,Flatten,BatchNormalization,Dropout, Activation
from gammatone_init import GammatoneInit
from model_config import *

In [13]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
models = {}
folders = os.listdir('./UrbanSound8K/audio')
frame_length = 5
overlapping_fraction = 0.2
dataset = make_frames_folder(folders,frame_length,overlapping_fraction)


processing file159750-8-0-5.wav
processing file160011-2-0-1.wav
processing file201652-5-5-1.wav
processing file178521-2-0-93.wav
processing file84359-2-0-9.wav
processing file27349-3-1-2.wav
processing file74458-9-1-5.wav
processing file203929-7-1-7.wav
processing file96169-9-1-55.wav
processing file74507-0-0-12.wav
processing file14387-9-0-19.wav
processing file147926-0-0-54.wav
processing file60591-2-0-11.wav
processing file76086-4-0-23.wav
processing file169098-7-3-1.wav
processing file96169-9-1-10.wav
processing file106015-5-0-17.wav
processing file159747-8-0-13.wav
processing file104817-4-0-11.wav
processing file27349-3-0-6.wav
processing file108187-3-3-0.wav
processing file177592-5-0-2.wav
processing file201652-5-2-4.wav
processing file203929-7-5-0.wav
processing file149254-9-0-29.wav
processing file194841-9-0-144.wav
processing file33849-3-3-0.wav
processing file159747-8-0-15.wav
processing file49808-3-1-8.wav
processing file76086-4-0-22.wav
processing file162541-1-2-0.wav
proce

In [17]:
print(len(dataset))

25243093


In [26]:
i = 0
for i in range(2):
    np.random.shuffle(dataset)
    X = dataset[:,0:frame_length]
    print(X)
    Y = dataset[:,frame_length]
    print(Y)
    X = X.reshape(X.shape[0], X.shape[1], 1)
    print(X)
    Y = tf.keras.utils.to_categorical(Y)
    print(Y)
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1,random_state=42)
    train_data = {'x_train':X_train,'y_train':Y_train}
print(train_data)


[[-2.98149548e-02  1.12078669e-04  3.51345204e-02  6.50495142e-02
   8.47708061e-02]
 [ 8.11767578e-03 -2.28881836e-03 -1.76391602e-02 -2.87475586e-02
  -3.04870605e-02]
 [ 4.05324027e-02 -4.70639467e-02 -1.02000358e-02  5.09981485e-03
  -4.36048256e-03]
 ...
 [ 3.92044848e-03  8.82330409e-04  3.92203266e-03  5.28529193e-03
   6.09259587e-03]
 [ 1.38108119e-01  3.21356148e-01  1.30310938e-01  1.41813248e-01
   1.09246403e-01]
 [-1.45628140e-03 -1.34047237e-03 -1.23522466e-03 -1.13921065e-03
  -1.02287577e-03]]
[0. 1. 4. ... 2. 7. 3.]
[[[-2.98149548e-02]
  [ 1.12078669e-04]
  [ 3.51345204e-02]
  [ 6.50495142e-02]
  [ 8.47708061e-02]]

 [[ 8.11767578e-03]
  [-2.28881836e-03]
  [-1.76391602e-02]
  [-2.87475586e-02]
  [-3.04870605e-02]]

 [[ 4.05324027e-02]
  [-4.70639467e-02]
  [-1.02000358e-02]
  [ 5.09981485e-03]
  [-4.36048256e-03]]

 ...

 [[ 3.92044848e-03]
  [ 8.82330409e-04]
  [ 3.92203266e-03]
  [ 5.28529193e-03]
  [ 6.09259587e-03]]

 [[ 1.38108119e-01]
  [ 3.21356148e-01]
  [ 1.

In [45]:
model = EnvNet(2,1)
optimizer =  tf.keras.optimizers.Adadelta()
num_epochs = 5
batch_size = 10
history = train_model(model,tf.keras.losses.mean_squared_logarithmic_error,optimizer,train_data,num_epochs,batch_size)
test_results = model.evaluate(X_test,Y_test)
models[i] = [model,history,test_results]
print (models[i])

Epoch 1/5


ValueError: in user code:

    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /home/nazzy/Development/soundLocalization_sandbox/environmental_sound_classification_1DCNN/model.py:37 call  *
        x = self.feature_extractor.call(inputs)
    /home/nazzy/Development/soundLocalization_sandbox/environmental_sound_classification_1DCNN/model_config.py:33 call  *
        x = self.l1(inputs)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1030 __call__  **
        outputs = call_fn(inputs, *args, **kwargs)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py:249 call
        outputs = self._convolution_op(inputs, self.kernel)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py:1012 convolution_v2
        return convolution_internal(
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py:1142 convolution_internal
        return op(
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:602 new_func
        return func(*args, **kwargs)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:602 new_func
        return func(*args, **kwargs)
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py:1884 conv1d
        result = gen_nn_ops.conv2d(
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py:969 conv2d
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:599 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:3557 _create_op_internal
        ret = Operation(
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:2041 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /home/nazzy/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: Negative dimension size caused by subtracting 64 from 5 for '{{node env_net_11/conv1d_70/conv1d}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 1, 2, 1], use_cudnn_on_gpu=true](env_net_11/conv1d_70/conv1d/ExpandDims, env_net_11/conv1d_70/conv1d/ExpandDims_1)' with input shapes: [?,1,5,1], [1,64,1,16].
